### ISSUE TITLE
help((

### ISSUE THREAD

**Issue by l4ckyguy** [fudanchii/ssh2dns#2]
please help. how can i get this app work?  i tried many solutions.. i need to proxy all traffic on my pi zero w, which i use as router... help please

**Comment by fudanchii** [comment]
hola, unfortunately this app will not proxy all your traffic, it's only capable to proxy your dns traffic by forwarding it through ssh tunnel, so you will need ssh server with key based authentication enabled. This app doesn't support password based ssh authentication.
